{{- if .Values.forwarder.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-forwarder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-forwarder
    spec:
      hostNetwork: true
      containers:
      - name: {{ .Release.Name }}-forwarder
        {{ if .Values.forwarder.use_local_image }}
        image: {{ .Values.forwarder.local_image }}
        {{ else }}
        image: {{ .Values.forwarder.image }}:{{ .Values.forwarder.tag }}
        {{ end }}
        env:
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: ADVERTISED_FORWARDER_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TASKS_PORT
          value: "{{ .Values.forwarder.tasksPort }}"
        - name: RESULTS_PORT
          value: "{{ .Values.forwarder.resultsPort }}"
        - name: COMMANDS_PORT
          value: "{{ .Values.forwarder.commandsPort }}"
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.forwarder.pullPolicy }}
        {{- if .Values.forwarder.resources }}
        resources:
{{ toYaml .Values.forwarder.resources | indent 10 }}
        {{- end }}
        ports:
          - containerPort: 8080  # Forwarder REST port
          - containerPort: {{ add .Values.forwarder.tasksPort 1 }}
            hostPort: {{ add .Values.forwarder.tasksPort 1 }}
          - containerPort: {{ add .Values.forwarder.resultsPort 1 }}
            hostPort: {{ add .Values.forwarder.resultsPort 1 }}
          - containerPort: {{ add .Values.forwarder.commandsPort 1 }}
            hostPort: {{ add .Values.forwarder.commandsPort 1 }}
          - containerPort: 55005 # Debug
            hostPort: 55005
        volumeMounts:
        - name: funcx-forwarder-secret
          mountPath: /home/funcx/.curve
          readOnly: true
      volumes:
      - name: funcx-forwarder-secret
        secret:
          secretName: funcx-forwarder-secretkey

{{- end }}
