---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-funcx-websocket-service
spec:
  ports:
   - port: 6000
     targetPort: 6000
     name: "tcp"
     protocol: TCP
  selector:
    app: {{ .Release.Name }}-funcx-websocket-service
  type: ClusterIP