apiVersion: v1
kind: Pod
metadata:
  name: redis-cli
  labels:
    app: redis-cli
spec:
  containers:
  - image: redis
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
